### ISSUE TITLE
How to set it up on with a startup script/config?

### ISSUE THREAD

**Issue by luni3359** [milaq/XMousePasteBlock#7] opened 2020-07-14 23:13 UTC
I'm not sure what's the best way to make it work from startup, is it with a ``.desktop`` file? Do I run it from a terminal? 
Sorry for making such a basic question.

**Comment by jonnotjohn** [comment] 2020-08-04 19:49
After installing, I added this line to my ~/.bashrc file
`xmousepasteblock &`

Then you can either log out/log in or run 
`source ~/.bashrc`
from the terminal and boom, it'll run in the background now.

**Comment by luni3359** [comment] 2020-08-04 20:11
Just out of curiosity, wouldn't this execute the program every time a new terminal is opened?

**Comment by luni3359** [comment] 2020-08-17 03:40
Previous guy deleted his comment. Anyway, it seems that adding it in Autostart (at least on KDE) is enough to make it run in login. I don't think it'd work in the login screen though.

I added it as a Desktop File by clicking on "Add Program..." in Autostart, under Startup and Shutdown. xmousepasteblock doesn't show up in the list, but if you type it out on your own and click OK it will get added. A ``xmousepasteblock.desktop`` file should be created under ``~/.config/autostart/``.

I'm going to leave this issue open because I still think it's not clear enough how to get this program running, and like I said, this method isn't system-wide.

**Comment by mestaritonttu** [comment] 2021-01-09 13:23
I tried creating a systemd unit:

```
/etc/systemd/system/xmousepasteblock.service
[Unit]
Description=Disable middle-mouse paste
Wants=network.target
After=syslog.target network-online.target

[Service]
Type=simple
ExecStart=/usr/bin/xmousepasteblock
Restart=on-failure
RestartSec=10
KillMode=process

[Install]
WantedBy=multi-user.target
```

However, when I start it, it fails with this in the journal:
`ERROR: Failed to connect to the X server`

On the other hand, it doesn't deactivate middle mouse paste if I launch it directly with /usr/bin/xmousepasteblock

This is on Arch Linux with https://aur.archlinux.org/packages/xmousepasteblock-git/

Klipper is disabled

**Comment by mestaritonttu** [comment] 2021-01-09 15:31
Got it working with autostart rather than systemd:

```
~/.config/autostart/xmousepasteblock.desktop

[Desktop Entry]
Type=Application
Exec=/usr/bin/xmousepasteblock
Hidden=false
Name=xmousepasteblock
Comment=Disable middle mouse button paste
```

**Comment by MostHated** [comment] 2021-03-12 00:09
I just want to confirm that this is correct. Is this supposed to be blocking when you run it? 

![](https://i.imgur.com/8in332x.png)


It only seems to block pasting about 2/3 or 3/4 of the time, so I can't tell if it is working as intended or not. I wanted to make sure it was before adding it to startup. 

<details>
<summary>System Details</summary>

```shell
OS: Pop!_OS 20.10 x86_64
Host: X570 AORUS ELITE -CF
Kernel: 5.8.0-7642-generic
Uptime: 10 hours, 54 mins
Packages: 3155 (dpkg), 34 (flatpak), 9 (snap)
Shell: zsh 5.8
Resolution: 1920x1080, 2560x1080, 1920x1080
DE: GNOME 3.38.3
WM: Mutter
WM Theme: Pop
Theme: Pop-dark [GTK2/3]
Icons: Pop [GTK2/3]
Terminal: alacritty
CPU: AMD Ryzen 9 3950X (32) @ 3.500GHz
GPU: NVIDIA GeForce RTX 2070
Memory: 10868MiB / 64321MiB
```

</details>

**Comment by milaq** [comment] 2021-04-06 15:32
Yes, it is not forking on startup.
Maybe I should add a short message about it beeing started correctly.

Otherwise closing here, as adding it to startup is specific to the DE/WM.

**Closed as completed by milaq** 2021-04-06 15:32 UTC

**Comment by sankalpmukim** [comment] 2023-10-13 10:53
I put it in my .profile script. Now it runs on start.
Because it was blocking, I put it with an &

`xmousepasteblock &`

**Comment by qadzek** [comment] 2024-03-01 19:48
I also encountered the `Failed to connect to the X server` error when using the systemd service.
The autostart script by @mestaritonttu does fix this issue on my system (Linux Mint, Cinnamon).
